### ISSUE TITLE
Completion provides no candidates

### ISSUE THREAD

**Issue by jwintz** [cute-jumper/company-qml#1]
Hello Junking,

This package is a very good idea, even though I do not like setting paths directly into init files, anyway, I wanted to give this package a try. So here is my config:

``` lisp
(setq qmltypes-parser-file-list `(
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/Controls/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/Dialogs/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/Extras/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/Layouts/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/LocalStorage/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/Particles.2/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/PrivateWidgets/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/Window.2/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick/XmlListModel/plugins.qmltypes"
      "/Users/jwintz/Development/qt/5.5/clang_64/qml/QtQuick.2/plugins.qmltypes"))

(require 'company-qml)

(eval-after-load 'company '(add-to-list 'company-backends 'company-qml))
(eval-after-load 'company '(add-to-list 'company-backends 'company-irony))
(eval-after-load 'company '(add-to-list 'company-backends 'company-irony-c-headers))
(eval-after-load 'company '(add-to-list 'company-backends 'company-cmake))

(add-hook          'c-mode-hook 'company-mode)
(add-hook        'c++-mode-hook 'company-mode)
(add-hook       'objc-mode-hook 'company-mode)
(add-hook 'emacs-lisp-mode-hook 'company-mode)
(add-hook      'cmake-mode-hook 'company-mode)
(add-hook       'html-mode-hook 'company-mode)
(add-hook        'qml-mode-hook 'company-mode)
```

Company provides no candidate.
- Is there any way I could debug this ?
- Why should `qmltypes-parser-file-list` be set _before_ the `require` statement ?
- Why not use the `qtpath` binary to infer the location of the qmltypes ?

Thanks.

**Comment by cute-jumper** [comment]
Oops...I kind of forget to improve this package after I've written some QML. Thank you for bringing it up!

To be honest, I'm not quite satisfied with this plugin even I wrote it, but it is usable and is better than its `auto-complete` counterpart so I put it in Melpa.

For your questions:

> Is there any way I could debug this ?

Yes. The most obvious way is to explicitly invoke `company-complete` to force company to complete. Sometimes company-mode is not triggered to give completions. And if you take a look at this Github repo, there are some `*-test.el` files, which provide some simple tests.

> Why should qmltypes-parser-file-list be set before the require statement ?

The reason is that the data structure is initialized when you `require` the file, but it needs to know list of files first in order to be initialized properly.

> Why not use the qtpath binary to infer the location of the qmltypes ?

I don't know about this and I can't find it in my Arch Linux. Can you provide more details?
Edit: It seems a typo. I found `qtpaths` in my system, but I'm still unsure how to infer the locations using `qtpaths`.

I also want to get rid of the path setting part because I don't like it either. The completions provided by this package are dictionary-based. I was thinking about hard-coding the completion information in the package for standard QML objects, and you don't have to set the `qmltypes-parser-file-list` unless you want completions for some third party libraries(such as some plasma libraries). I haven't done this yet because I'm not sure hard-coding is a good idea. But it seems it's more convenient for the user if he/she only needs completions for standard QML objects.

Do share your opinions!

**Comment by cute-jumper** [comment]
Ping...Any updates?

**Comment by jwintz** [comment]
Sorry, here I am back from vacation. I've been writing a full QML project, the last couple of weeks but company-qml was not working and I had no time to debug it. I'll try to investigate a little further now. Also, I am not very happy with qml-mode which is a bit outdated and indents in a very strange manner.

I'll keep you posted.

**Comment by stardiviner** [comment]
Can't get complete candidates too.
Environment:
- Arch Linux
- Emacs 24.5.1

**Comment by cute-jumper** [comment]
@stardiviner Can you provide more details? For example, the minimal QML code that doesn't work?

**Comment by stardiviner** [comment]
@cute-jumper I followed the examples in README, all of that three examples do not work.

**Comment by cute-jumper** [comment]
@stardiviner It works fine on my laptop, which has the same environment as yours(Arch with Emacs 24.5.1). Make sure `qmltypes-parser-file-list` is set correctly. Sometimes it may have some delay triggering the company completion. Try to use `company-complete` to force company to complete.

**Comment by stardiviner** [comment]
You're right, after I put set `qmltypes-parser-file-list` in `use-package`'s `:init` section. It can work now. Thanks.

**Comment by cute-jumper** [comment]
@jwintz @stardiviner FYI, this package should now work out of box and unless you want to override the default completions, setting `qmltypes-parser-file-list` is not necessary now.

**Comment by stardiviner** [comment]
Confirmed.

**Comment by hello-code** [comment]
Can't get complete candidates too!!
Environment:
- Debian Jessie
- Emacs 25.1.50

```
;;; init-qml --- qml
;;; Commentary:
;; https://github.com/cute-jumper/company-qml/issues/1
;;; Code:

;; qml mode
(autoload 'qml-mode "qml-mode" "Editing Qt Declarative." t)
(add-to-list 'auto-mode-alist '("\\.qml$" . qml-mode))

;; company-qml
;;(exec-path-from-shell-copy-env "QML_PATH")
(setq qmltypes-parser-file-list ;;company-qml-default-qmltypes-files;;company-qml-extra-qmltypes-files
      '(
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/Controls/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/Dialogs/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/Extras/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/Layouts/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/LocalStorage/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/Particles.2/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/PrivateWidgets/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/Window.2/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick/XmlListModel/plugins.qmltypes"
        "/home/jack/app/Qt5/5.5/gcc_64/qml/QtQuick.2/plugins.qmltypes"
        ))
(require 'company-qml)
(eval-after-load 'company '(add-to-list 'company-backends 'company-qml))

(provide 'init-qml)
;;; init-qml.el ends here
```

Thanks!

**Comment by cute-jumper** [comment]
@hello-code Sorry for the late reply. I don't think you need the `(setq qmltypes-parser-file-list ...)` line. For standard QML objects, company-qml should now work out of the box.

**Comment by hello-code** [comment]
Thanks! It works!

```
(use-package company-qml
     :config
    (add-hook
     'qml-mode-hook
     '(lambda()
        (set (make-local-variable 'company-backends)'(company-qml))
        (company-mode)))
```
